language: cpp
dist: bionic

compiler: gcc

addons:
  apt:
    packages: cmake build-essential pkg-config libgoogle-perftools-dev libboost-all-dev wget unzip libgtest-dev

before_script:
    - mkdir build_gtest && cd build_gtest
    - cmake -DBUILD_SHARED_LIBS=ON /usr/src/gtest && make && sudo make install
    - cd ..
    - rm -Rf build_gtest
    - mkdir models
    - alias python='python3'
    - scripts/get_data.sh
    - scripts/get_third_party.sh
    - source compile.env
    - mkdir build
    - cd build
    - cmake -DBUILD_TEST=ON -DCMAKE_BUILD_TYPE=Debug ..

script: 
    - make

after_success:
    - ./hflt
    - wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate "https://docs.google.com/uc?export=download&id=1i0rr-ogZ2MDYPpUMBsg-2PV7zVddivJ0" -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1i0rr-ogZ2MDYPpUMBsg-2PV7zVddivJ0" -O ../models/sst2_trained.tar.gz && rm -rf /tmp/cookies.txt
    - curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh
    - chmod +x /tmp/miniconda.sh
    - /tmp/miniconda.sh -b -p ~/miniconda3
    - ~/miniconda3/bin/conda install -y python=3.7 numpy
    - ~/miniconda3/bin/conda install -y -c pytorch pytorch
    - export PATH $(realpath ~/miniconda3/conda/bin):$PATH
    - pip install transformers
    - cd ../models && tar xzvf sst2_trained.tar.gz && cd ..
    - python scripts/trace_albert.py
    - cd build
    - head -n 100 ../data/SST-2/dev.tsv > ../data/SST-2/dev-small.tsv
    - ./hlft ../models/sst2_trained ../data/SST-2/dev-small.tsv 
    - ctest -VV
